# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  gatsby:
    image: gatsby
    build:
      context: .
      dockerfile: docker/gatsby/Dockerfile
    ports:
      - "9000:9000"
  sqlserver:
    image: sqlserver
    build:
      context: ./docker/sql-server
      dockerfile: Dockerfile
    ports:
      - 1000:1433
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 5000:5000