apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gatsby
  name: gatsby
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gatsby
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gatsby
    spec:
      containers:
        - image: wtrvgl/gatsby
          name: gatsby
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
