---
new_page_extension: md
auto_deploy: false
admin_path: "/client/static/admin"
<<<<<<< HEAD:.forestry/settings.yml
webhook_url: 
sections:
- type: directory
  path: client/src/data/products
  label: test
  create: all
  match: "**/*"
upload_dir: client/images
=======
webhook_url:
sections:
upload_dir: uploads
>>>>>>> forestry-cms:client/.forestry/settings.yml
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
sections:
  - type: directory
    path: src/data/products
    label: Products
    create: documents
    match: "**/*"
    templates:
      - product