---
new_page_extension: md
auto_deploy: false
admin_path: "/client/static/admin"
webhook_url: 
sections:
- type: directory
  path: client/src/data/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - product
upload_dir: client/src/images
public_path: "/uploads"
front_matter_path: client/src/images
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
