---
label: Product
hide_body: false
fields:
- type: text
  name: productName
  label: productName
- type: text
  name: productType
  label: productType
- type: text
  name: productCategory
  label: productCategory
- type: list
  name: secondaryProductType
  label: secondaryProductType
- type: text
  name: price
  label: price
- type: boolean
  name: featuredProduct
  label: featuredProduct
- type: file
  name: featuredImage
  label: featuredImage
- type: image_gallery
  name: images
  label: images
